server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Nicholas2015/cloud-sample.git
          search-paths: config
          username: 799327210@qq.com
          password: sun,910929
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

